"""Gmail-specific tool wrappers and provider helpers."""

from .gmail_main import (
    gmail_chatty_threads,
    gmail_create_label,
    gmail_create_draft,
    gmail_create_draft_with_attachments,
    gmail_create_filter,
    gmail_delete_label,
    gmail_delete_filter,
    gmail_enable_forwarding,
    gmail_get_filter,
    gmail_list_messages,
    gmail_list_labels,
    gmail_list_filters,
    gmail_modify_message_labels,
    gmail_modify_thread_labels,
    gmail_search_messages,
    gmail_search_threads,
    gmail_update_signature,
    gmail_send_email,
    gmail_send_email_with_attachments,
    gmail_total_counts,
    gmail_unread_count,
    gmail_unread_summary,
)

GMAIL_TOOLS = [
    gmail_total_counts,
    gmail_unread_count,
    gmail_unread_summary,
    gmail_list_labels,
    gmail_create_label,
    gmail_delete_label,
    gmail_modify_message_labels,
    gmail_modify_thread_labels,
    gmail_enable_forwarding,
    gmail_create_filter,
    gmail_list_filters,
    gmail_get_filter,
    gmail_delete_filter,
    gmail_list_messages,
    gmail_search_messages,
    gmail_search_threads,
    gmail_chatty_threads,
    gmail_create_draft,
    gmail_send_email,
    gmail_update_signature,
    gmail_create_draft_with_attachments,
    gmail_send_email_with_attachments,
]

__all__ = [
    "gmail_total_counts",
    "gmail_unread_count",
    "gmail_unread_summary",
    "gmail_list_labels",
    "gmail_create_label",
    "gmail_delete_label",
    "gmail_modify_message_labels",
    "gmail_modify_thread_labels",
    "gmail_enable_forwarding",
    "gmail_create_filter",
    "gmail_list_filters",
    "gmail_get_filter",
    "gmail_delete_filter",
    "gmail_list_messages",
    "gmail_search_messages",
    "gmail_search_threads",
    "gmail_chatty_threads",
    "gmail_create_draft",
    "gmail_send_email",
    "gmail_update_signature",
    "gmail_create_draft_with_attachments",
    "gmail_send_email_with_attachments",
    "GMAIL_TOOLS",
]
